import { jsPDF } from "jspdf";

export function downloadSIPReport({
  monthlyInvestment,
  annualReturn,
  years,
  investedAmount,
  wealthGained,
  maturityValue,
}) {
  const doc = new jsPDF();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("FinanceWithCSR", 20, 20);

  doc.setFontSize(16);
  doc.text("SIP Investment Report", 20, 35);

  doc.setDrawColor(37, 99, 235);
  doc.line(20, 40, 190, 40);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);

  let y = 55;

  doc.text(
    `Monthly Investment : ₹ ${monthlyInvestment.toLocaleString("en-IN")}`,
    20,
    y
  );

  y += 10;

  doc.text(`Expected Return : ${annualReturn}%`, 20, y);

  y += 10;

  doc.text(`Investment Period : ${years} Years`, 20, y);

  y += 20;

  doc.setFont("helvetica", "bold");

  doc.text(
    `Total Investment : ₹ ${investedAmount.toLocaleString("en-IN")}`,
    20,
    y
  );

  y += 12;

  doc.text(
    `Estimated Returns : ₹ ${wealthGained.toLocaleString("en-IN", {
      maximumFractionDigits: 0,
    })}`,
    20,
    y
  );

  y += 12;

  doc.setFontSize(16);

  doc.text(
    `Maturity Value : ₹ ${maturityValue.toLocaleString("en-IN", {
      maximumFractionDigits: 0,
    })}`,
    20,
    y
  );

  y += 25;

  doc.setFontSize(11);
  doc.setFont("helvetica", "italic");
  doc.text(
    "Generated by FinanceWithCSR Calculator",
    20,
    y
  );

  doc.save("FinanceWithCSR-SIP-Report.pdf");
}